project:
  type: book
  output-dir: _book
book:
  title: "US Credit Card Partnerships"
  author: "Kathryn Dobinson"
  date: "18/12/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Data"
      chapters:
        - data_ffiec.qmd
        - data_partners.qmd 
        - data_fed.qmd               
    - part: "Event Study"
      chapters:
        - model_event.qmd   
        - model_market.qmd 
        - model_arima.qmd 
        - model_hierarchy_event.qmd
        - model_ml.qmd
    - references.qmd   
    - part: "Appendix"
      chapters:
        - data_banks.qmd
bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    code-tools: true
    code-summary: "Show the code"
  pdf:
    documentclass: scrreprt



