project:
  type: book
  output-dir: _book
book:
  title: "US Credit Card"
  author: "Kathryn Dobinson"
  date: "18/12/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Data"
      chapters:
        - data_ffiec.qmd
        - data_banks.qmd
        - data_partners.qmd        
        - data_fed.qmd
    - part: "Models"
      chapters:
        - event.qmd      
bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    code-tools: true
    code-summary: "Show the code"
  pdf:
    documentclass: scrreprt



