project:
  type: book
  output-dir: docs
book:
  title: "US Credit Card Partnerships"
  author: "Kathryn Dobinson"
  date: "22/03/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Data"
      chapters:
        - data_ffiec.qmd
        - data_partners.qmd 
        - data_fed.qmd               
    - part: "Event Study"
      chapters:
        - model_event.qmd   
        - model_market.qmd 
        - model_arima.qmd 
        - model_hierarchy_event.qmd
        - model_ml.qmd
        - model_event_summary.qmd
    - part: "Hierarchical Study"
      chapters:
        - model_hierarchy.qmd
        - model_hierarchy_extra.qmd
    - references.qmd   
    - part: "Appendix"
      chapters:
        - data_banks.qmd
        - data_final_event.qmd
        - data_final_hierarchy.qmd
bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    code-tools: true
    code-summary: "Show the code"
  pdf:
    documentclass: scrreprt

execute: 
  freeze: auto

